# 设置博客站点基本信息
base_info:
  # 设置博客站点的标题
  title: Thornboo Blog
  # 设置作者名称
  author: thornboo
  url: https://thornboo.github.io/

# 自定义配置Keep主题的样式
style:
  # 设置博客站点主题色，支持 十六进制、rgb 和 rgba 颜色格式
  primary_color: "#cb3e3e"
  # 设置博客站点头部 LOGO
  logo: https://cdn.staticaly.com/gh/thornboo/blog-image-bed@master/blog-info/favicons-32.7kivdj6o7ss0.webp
  # 设置博客站点作者头像
  avatar: https://cdn.staticaly.com/gh/thornboo/blog-image-bed@master/blog-info/博客作者头像.pusoqr2t06o.webp
  # 设置博客站点 favicon 图标
  favicon: https://cdn.staticaly.com/gh/thornboo/blog-image-bed@master/blog-info/favicons-32.7kivdj6o7ss0.webp
  # 设置博客站点的字体样式
  font_family: PingFangSC
  # 设置鼠标悬浮时的样式
  hover:
    shadow: true
    scale: true
  # 设置首屏模块
  first_screen:
    enable: true
    background_img: /images/bg.svg
    description: 主动思考，积极行动。
    # 设置头部是否透明
    header_transparent: false
  # 设置页面滚动时的样式
  scroll:
    progress_bar:
      enable: false
    percent:
      enable: true

# 设置首屏里面配置第三方社交链接
social_contact:
  enable: true
  links:
    github: https://github.com/thornboo
    weixin: img | https://cdn.staticaly.com/gh/thornboo/blog-image-bed@master/blog-info/weChat-QR-Code.2yisnac4u120.webp
    qq: img| https://cdn.staticaly.com/gh/thornboo/blog-image-bed@master/blog-info/QQ-QR-Code.3ejsm2p1oy60.webp
    weibo:
    zhihu:
    twitter:
    facebook:
    email: zhaozhuang1210@gmail.com

# 配置博客站点的头部导航菜单
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
  # Changelog: /changelog

# 设置首页文章块底部的标签和分类信息显示
home_article:
  # 设置显示文章分类
  category:
    enable: true
    limit: 3
  # 设置显示文章标签
  tag:
    enable: true
    limit: 5

# 设置文章内容页
post:
  # 设置作者标识
  author_label:
    enable: true
    auto: true
    custom_label_list: ["全栈工程师"]
  # 设置文章字数统计和计算阅读时长
  word_count:
    enable: true
    wordcount: true
    min2read: true
  # 设置图片位置
  article_img_align: left
  # 设置是否开启文章内容页的文章版权信息
  copyright_info: true

# 开启代码块工具
code_block:
  tools:
    enable: true
    style: mac
  highlight_theme: default

# 设置文章 TOC 目录结构
toc:
  enable: true
  number: false
  expand_all: false
  init_open: true

# 设置网站计数
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true

# 设置站内搜索功能
local_search:
  enable: true
  preload: true # 在页面加载时预加载搜索数据

# 设置评论系统
comment:
  enable: true
  use: gitalk # values: valine | gitalk | twikoo

  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    appid:
    appkey:
    placeholder:

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: thornboo
    repository: thornboo.github.io
    client_id: 5a587300d1cc759218a8
    client_secret: ca552df0666567b315934034de182a9955f54441

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    env_id:
    region:

# RSS订阅功能
rss:
  enable: true

# 设置图片懒加载
lazyload:
  enable: true

# 设置CDN加速功能
cdn:
  enable: true
  provider: jsdelivr  # Option values: jsdelivr | unpkg

# 设置Keep主题的PJAX功能，带来单页应用体验
pjax:
  enable: true

# 设置网站底部的信息展示
footer:
  since: 2022
  icp:
  site_deploy:
    enable: true
    provider: github
    url: https://github.com

# Keep version
version: 3.4.5
